import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';

const inter = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'MRNK',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className='scroll-smooth' lang='en'>
			<body className={`${inter.className} text-white bg-[#161513]`}>
				<Header />
				{children}
				<Footer />
				<Toaster />
			</body>
		</html>
	);
}
